packages:
  # 应用
  - apps/*
  # 共享包
  - packages/*

catalog:
  # react
  react: ^18.3.1
  react-dom: ^18.3.1
  react-router-dom: ^6.28.1
  '@types/react': ^18.3.18
  '@types/react-dom': ^18.3.5
  # ui
  dayjs: ^1.11.13
  antd: ^5.22.6
  ahooks: ^3.8.4
  antd-style: ^3.7.1
  '@ant-design/colors': ^8.0.0
  '@ant-design/cssinjs': ^1.22.1
  '@ant-design/icons': ^5.5.2
  # lint
  eslint: ^9.33.0
  eslint-import-resolver-alias: ^1.1.2
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  '@eslint/js': ^9.33.0
  globals: ^16.3.0
  # format
  prettier: ^3.6.2
  # build
  vite: ^4.5.5
  '@babel/core': ^7.26.0
  '@babel/plugin-syntax-flow': ^7.26.0
  '@babel/plugin-transform-react-jsx': ^7.25.9
  '@babel/preset-env': ^7.26.0
  '@vitejs/plugin-react-swc': ^3.11.0
  'typescript': '^5.9.2'
  'less': ^4.4.0
